#!/bin/bash
source ../../localProjectPath.sh
source $_PROJECT_PATH/globalVariables.sh

_CD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
_GENERATED_PATH=$_CD/generated/$_USER_SPECIFIC
mkdir -p $_GENERATED_PATH
cd $_GENERATED_PATH

tar xf $_ASAP_SOURCE
tar xf $_REPOSITORY_DIR/asap/${_ASAP_SOURCE_FILENAME}-patch.tar.gz

cd ${_ASAP_SOURCE_FILENAME}

# mkdir -p debug
# cd debug

# $_CMAKE -G "${_COMPILER_NAME}" -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=${_MYENV_APP_INSTALL} $_GENERATED_PATH/$_ASAP_SOURCE_FILENAME
# $_CMAKE --build .

# cd ..

mkdir -p release
cd release

_OPTIONS="-DBUILD_DIAG_PATHOLOGY_EXECUTABLES=ON -DBUILD_DIAG_PATHOLOGY_IMAGEPROCESSING=ON -DBUILD_DIAG_PATHOLOGY_TESTS=ON -DBUILD_DIAG_PATHOLOGY_WORKSTATION=ON -DBUILD_MULTIRESOLUTIONIMAGEINTERFACE_VSI_SUPPORT=ON -DWRAP_MULTIRESOLUTIONIMAGEINTERFACE_PYTHON=ON -DWRAP_WHOLESLIDEFILTERS_PYTHON=ON"

# $_CMAKE -G "${_COMPILER_NAME}" -DTIFF_INCLUDE_DIR=$_LIB_TIFF_INCLUDE_DIR -DTIFF_LIBRARY=$_LIB_TIFF_DLL_LIB -DDCMTKJPEG_INCLUDE_DIR=$_DCMTK_INCLUDE_DIR -DOPENSLIDE_INCLUDE_DIR=$_OPENSLIDE_INCLUDE_DIR -DOPENSLIDE_LIBRARY=$_OPENSLIDE_DLL_LIB -DUNITTEST_INCLUDE_DIR=$_UNITTESTPP_INCLUDE_DIR -DUNITTEST_LIBRARY=$_UNITTESTPP_DLL_LIB	-DUNITTEST_LIBRARY_DEBUG=$_UNITTESTPP_DLL_LIB_DEBUG ${_OPTIONS} -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=${_MYENV_APP_INSTALL} $_GENERATED_PATH/$_ASAP_SOURCE_FILENAME
$_CMAKE -G "${_COMPILER_NAME}" -DTIFF_INCLUDE_DIR=$_LIB_TIFF_INCLUDE_DIR -DTIFF_LIBRARY=$_LIB_TIFF_DLL_LIB -DDCMTKJPEG_INCLUDE_DIR=$_DCMTK_INCLUDE_DIR -DOPENSLIDE_INCLUDE_DIR=$_OPENSLIDE_INCLUDE_DIR -DOPENSLIDE_LIBRARY=$_OPENSLIDE_DLL_LIB -DUNITTEST_INCLUDE_DIR=$_UNITTESTPP_INCLUDE_DIR -DUNITTEST_LIBRARY=$_UNITTESTPP_DLL_LIB	-DUNITTEST_LIBRARY_DEBUG=$_UNITTESTPP_DLL_LIB_DEBUG ${_OPTIONS} -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${_MYENV_APP_INSTALL} $_GENERATED_PATH/$_ASAP_SOURCE_FILENAME
# $_CMAKE -L $_GENERATED_PATH/$_ASAP_SOURCE_FILENAME # display the configuration variables
$_CMAKE --build . --target install

cd ..

cd ..

source $_PROJECT_PATH/common/deleteFolder.sh ${_ASAP_SOURCE_FILENAME}

if [ "$1" != "-nopause" ]; then
	read -n1 -r -p "Press any key to continue..."
fi
